{{- if not .Values.postgresql.install -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.webserver.database.host }}
  labels:
    app: {{ template "votacultura.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
   postgresql-password: {{ .Values.webserver.database.password | b64enc }}
{{- end -}}
